FROM node:6.11.2-alpine

COPY package.json /frontend/

WORKDIR frontend

RUN yarn install

COPY public/ /frontend/public/

COPY src/ /frontend/src/

RUN yarn build

RUN yarn global add serve

CMD serve -s build

EXPOSE 5000
